apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: namespace-nginx
  labels:
    app: app-pod-nginx
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: container-nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  imagePullSecrets:
    - name: myregistrykey
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]
      envFrom:
        - configMapRef:
            name: config-map
        - secretRef:
            name: secret-app
