apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: namespace-nginx
  labels:
    app: app-pod-nginx
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: container-nginx
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "256Mi"
          cpu: 1
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  nodeSelector:
    size: Large
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: size
                operator: In | NotIn | Exists
                values:
                  - Large
                  - Medium
  imagePullSecrets:
    - name: myregistrykey
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]
      envFrom:
        - configMapRef:
            name: config-map
        - secretRef:
            name: secret-app
  serviceAccount: dashboard-sa
  automountServiceAccountToken: false
