apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: namespace-nginx
  labels:
    app: app-service-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app-pod-nginx